endpointList = ["http://127.0.0.1:26657"]
gasPrice = "0.005untrn"
taskTicker = 60  # seconds
poolAddr = ""
stakeManagerAddr = ""
keyringDir = ""
keyringBackend = "file"
keyName = ""
runForEntrustedPool = false